/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import static spark.Spark.*;

public class App {
    public static void main(String[] args) {
        Charge pages = new Charge();
        Auth authentication = new Auth();
        port(8085);
        staticFiles.location("/FRONTEND");
        
        get("/", (req, res) -> {
            res.type("text/html");
            return pages.chargeHTML("FRONTEND/index.html"); 
        });
        get("/login", (req, res) -> {
            res.type("text/html");
            return pages.chargeHTML("HTML/login.html");
        });
        get("/areas", (req, res) -> {
            res.type("text/html");
            return pages.chargeHTML("HTML/areas.html");
        });
        get("/sponsors", (req, res) -> {
            res.type("text/html");
            return pages.chargeHTML("HTML/sponsors.html");
        });
        get("/actividades", (req, res) -> {
            res.type("text/html");
            return pages.chargeHTML("HTML/activities.html");
        });

        post("/login/submit/init", (req, res) -> {
            boolean trying = authentication.tryAuth(req.queryParams("email"), req.queryParams("password"), res);
            if(!trying){
                res.redirect("/login");
                return null;
            }
            res.redirect("/");
            return null;
        });
    }
}
